/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.JTable;
import operatingsystemscheduler.ProcessSimulator;
/**
 *
 * @author Rajith Bhanuka
 */
public class Simulation extends javax.swing.JFrame {

    /**
     * Creates new form Simulation
     */
    public Simulation() {
        initComponents();
        labelSimTime.setText(Integer.toString(Controller.getSimTime()));
        
        String[] columns = {"PID","Arrival Time","Burst Time","Remaining Time"};
        String[][] procDet = Controller.getProcessDetails();
        this.processTable = new JTable(procDet,columns);
        jScrollPane1.setViewportView(processTable);
        
        String[] columnsReady = {"PID","Remaining Time"};
        String[][] readyDet = Controller.getReadyQueue();
        this.readyTable = new JTable(readyDet,columnsReady);
        jScrollPane2.setViewportView(readyTable);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        processTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelSimTime = new javax.swing.JLabel();
        labelCurrent = new javax.swing.JLabel();
        labelPId = new javax.swing.JLabel();
        buttonEnd = new javax.swing.JButton();
        button1s = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        readyTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableFinished = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        processTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Process ID", "Arrival TIme", "Burst Time", "Remaing Time"
            }
        ));
        jScrollPane1.setViewportView(processTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 720, 210));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Process Table :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel2.setText("Simulation Time");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setText("Current Time");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane().add(labelSimTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 30, 10));
        getContentPane().add(labelCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 20, 10));
        getContentPane().add(labelPId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 30, 10));

        buttonEnd.setText("Jump to End");
        buttonEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEndActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        button1s.setText("Proceed (1s)");
        button1s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1sActionPerformed(evt);
            }
        });
        getContentPane().add(button1s, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        readyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(readyTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 450, 210));

        jLabel4.setText("Current Process ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Finished Processes :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel6.setText("Shortest Remaining Time First Simulation");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Ready Queue :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        tableFinished.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PID", "Waiting Time", "Turnaround Time", "Finished Time"
            }
        ));
        jScrollPane3.setViewportView(tableFinished);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 490, 210));

        jButton1.setText("View Logs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, -1));

        setBounds(0, 0, 1002, 615);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEndActionPerformed
      
        while(Controller.getTime()!=Controller.getSimTime()){
            this.button1sActionPerformed(evt);
        }
    }//GEN-LAST:event_buttonEndActionPerformed

    private void button1sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1sActionPerformed
        Controller.incrementTime();
        labelCurrent.setText(Integer.toString(Controller.getTime()));
        
        String[] columnsPro = {"PID","Arrival Time","Burst Time","Remaining Time"};
        String[][] procDet = Controller.getProcessDetails();
        this.processTable = new JTable(procDet,columnsPro);
        jScrollPane1.setViewportView(processTable);
        

        if(Controller.getSimTime()==Controller.getTime()){
            this.button1s.setEnabled(false);
            this.buttonEnd.setEnabled(false);
        
        }
        
        this.labelPId.setText(Integer.toString(Controller.getCurrentProcessID()));
        
        String[] columnsReady = {"PID","Remaining Time"};
        String[][] readyDet = Controller.getReadyQueue();
        this.readyTable = new JTable(readyDet,columnsReady);
        jScrollPane2.setViewportView(readyTable);
        
        String[] columnsFinished = {"PID","Waiting Time","Turnaround Time","Finished Time"};
        String[][] finishedDet = Controller.getFinishedProcessDetails();
        this.tableFinished = new JTable(finishedDet,columnsFinished);
        jScrollPane3.setViewportView(tableFinished);
        
    }//GEN-LAST:event_button1sActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Logs logView = new Logs();
        logView.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1s;
    private javax.swing.JButton buttonEnd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelCurrent;
    private javax.swing.JLabel labelPId;
    private javax.swing.JLabel labelSimTime;
    private javax.swing.JTable processTable;
    private javax.swing.JTable readyTable;
    private javax.swing.JTable tableFinished;
    // End of variables declaration//GEN-END:variables
}
