/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.JTable;
/**
 *
 * @author Rajith Bhanuka
 */
public class Simulation extends javax.swing.JFrame {

    /**
     * Creates new form Simulation
     */
    public Simulation() {
        initComponents();
        labelSimTime.setText(Integer.toString(Controller.getSimTime()));
        
        String[] columns = {"PID","Arrival Time","Burst Time","Remaining Time"};
        String[][] procDet = Controller.getProcessDetails();
        this.processTable = new JTable(procDet,columns);
        jScrollPane1.setViewportView(processTable);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        processTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelSimTime = new javax.swing.JLabel();
        labelCurrent = new javax.swing.JLabel();
        labelPId = new javax.swing.JLabel();
        buttonEnd = new javax.swing.JButton();
        button1s = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        processTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Process ID", "Arrival TIme", "Burst Time", "Remaing Time"
            }
        ));
        jScrollPane1.setViewportView(processTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 140));

        jLabel1.setText("Current Process ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel2.setText("Simulation Time");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setText("Current Time");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        getContentPane().add(labelSimTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));
        getContentPane().add(labelCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));
        getContentPane().add(labelPId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        buttonEnd.setText("Jump to End");
        buttonEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEndActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        button1s.setText("Proceed (1s)");
        button1s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1sActionPerformed(evt);
            }
        });
        getContentPane().add(button1s, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEndActionPerformed
      
        while(Controller.getTime()!=Controller.getSimTime()){
            this.button1sActionPerformed(evt);
        }
    }//GEN-LAST:event_buttonEndActionPerformed

    private void button1sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1sActionPerformed
        Controller.incrementTime();
        labelCurrent.setText(Integer.toString(Controller.getTime()));
        String[] columns = {"PID","Arrival Time","Burst Time","Remaining Time"};
        String[][] procDet = Controller.getProcessDetails();
        this.processTable = new JTable(procDet,columns);
        jScrollPane1.setViewportView(processTable);
        

        if(Controller.getSimTime()==Controller.getTime()){
            this.button1s.setEnabled(false);
            this.buttonEnd.setEnabled(false);
        
        }
        
        this.labelPId.setText(Integer.toString(Controller.getCurrentProcessID()));
    }//GEN-LAST:event_button1sActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1s;
    private javax.swing.JButton buttonEnd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCurrent;
    private javax.swing.JLabel labelPId;
    private javax.swing.JLabel labelSimTime;
    private javax.swing.JTable processTable;
    // End of variables declaration//GEN-END:variables
}
